name: hostel_manager
description: A hostel management app using Flutter and SQLite.

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.3.0
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
